export class userDetail
{
  USERID : number;
  Username :  string;
  Password :  string;
  FIRSTNAME :  string;
  LASTNAME : string;
  COMPANYNAME :  string;
  PHONE : string;
  FAX :  string;
  EMAIL : string;
  IsActiveTime : string;
  ISACTIVE : boolean;
  ISDELETED : boolean;
  WORKEMAIL :  string;
  CELL :  string ;
  CITY :  string;
  STATE :  string;
  ADDRESS :  string;
  ZIP :  string;
  BIRTHDAY :  string;
  LICENSENUMBER : string;
  DBA : string;
  NPI : string;
  USERTYPE :  string;
  LOGINATTEMPT : number;
  EContactName1 :  string;
  EContactPhone1 : string;
  EContactName2 :  string;
  EContactPhone2 : string;
  GroupName : string;
  UserPosition :string;
  UserHire : string;
  Extention :string;
  DepartmentId :  string;
  AssingBrokerID : string;
  LunchTime : string;
  AssignFacilityParentID : string;
  AssignFacilityID :string;
  AssignReferrerID : string;
  IsNotReadBarcode : boolean;
  IsDoNotSplit : boolean;
  UserTermination : string;
  Hours : string;
  OrdSchedLock : string; 
  OrdSchedLockTime :  string;
  UserSlackID : string;
  UserDuties :  string;
  EmailVerificationCode : string;
  ResetPasswordCode : string;
  ResetPasswordExpiry : string;
}